### ISSUE TITLE
Mod Suggestion - OSA/OSex/OStim package

### ISSUE THREAD

**Issue by kolirios** [TwistedModding/LSSE#11]
OSA - https://www.nexusmods.com/skyrimspecialedition/mods/17217
OSex - https://www.nexusmods.com/skyrimspecialedition/mods/17209
OStim - https://www.nexusmods.com/skyrimspecialedition/mods/40725
OCum - https://www.nexusmods.com/skyrimspecialedition/mods/45990

**Comment by TwistedModding** [comment]
Not using these.
