### ISSUE TITLE
Mod Suggestion - More Nasty Critters

### ISSUE THREAD

**Issue by nervouscapybara** [TwistedModding/LSSE#12]
https://www.loverslab.com/files/file/4130-more-nasty-critters-slal-edition/

Hi Twisted, was hoping MNC could be added to provide a base for additional modifications by people like me who aren't as familiar with building modlists. It should be unobtrusive to people who don't want to use it, but very much appreciated by people who do. Torhild very kindly made an MNC fork for me back in the day, but I totally understand if you decide not to include it. Cheers and thanks for your work.

**Comment by TwistedModding** [comment]
Yeah I planned on adding this already

**Comment by TwistedModding** [comment]
done
