### ISSUE TITLE
Mod Suggestion - Equipable Underwear For Everyone/Under There

### ISSUE THREAD

**Issue by SeraphSmut** [TwistedModding/LSSE#13]
**Equipable Underwear For Everyone** https://www.nexusmods.com/skyrimspecialedition/mods/17183
_Or_
**Under There** https://www.nexusmods.com/skyrimspecialedition/mods/45566

These two mods help with immersion, and if you have any concern about flying under the radar around nosy partners/roomies/etc. This also gives players one easy way to avoid unwanted nudity from male characters anytime they loot body slot armor. 

Maybe covers some aspect of this user's concerns in closed issues. https://github.com/TwistedModding/LSSE/issues/10

**Comment by TwistedModding** [comment]
Not including, if you dont want nudity play LS3
