### ISSUE TITLE
Mod Suggestions for LSSE3

### ISSUE THREAD

**Issue by LightAdept** [TwistedModding/LSSE#18]
There doesn't appear to be many thing's i'd want to add that haven't already been suggested, that being said

Public hair that matches your hair color, for NPCs too:
https://www.loverslab.com/files/file/4111-2018-05-15-markdfs-patcher-reuploaded-sse-the-painted-lady-color-matching-pubic-hairs/
https://www.loverslab.com/files/file/10318-sos-female-pubic-hairs-colored-for-npcs/

Left Hand Rings, I don't know why none of these lists want this mod....:
https://www.nexusmods.com/skyrimspecialedition/mods/3240?tab=files

About the only armor mod i could think of adding was this one, because it makes sense, forsworn topless armor:
https://www.nexusmods.com/skyrimspecialedition/mods/16434

**Comment by TwistedModding** [comment]
I'm not adding any of these. 
1st one, there will not be any pubic hair
2nd one balance issues
3rd one, topless forsworn running around doesnt make too much sense(now i know skimpy armors dont either but i dont want naked people running around)
