### ISSUE TITLE
Mod Suggestion - Amorous Adventures

### ISSUE THREAD

**Issue by Deth24** [TwistedModding/LSSE#2]
https://www.loverslab.com/topic/109518-amorous-adventures-34-sse-for-lovers-lab/

Also AA Extended
https://www.loverslab.com/files/file/8849-amorous-adventures-extended-sse/

**Comment by Deth24** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/39163?tab=files

This is an updated version I believe

**Comment by Deth24** [comment]
Similar mod cause Sexlab Solutions
https://www.loverslab.com/files/file/1635-sexlab-solutions-507-01-december-2017/

**Comment by TwistedModding** [comment]
Not adding amorous adventures because its more of a meme mod than anything imo. I will add sexlab solutions though.

**Comment by TwistedModding** [comment]
done
