### ISSUE TITLE
Mod requests for LSSE

### ISSUE THREAD

**Issue by dindrenzi** [TwistedModding/LSSE#3]
(Sexlab) Werewolves
Sexual Vampire Feed
Sexlab Deadly Drain

**Comment by dindrenzi** [comment]
(Sexlab) Werewolves https://www.loverslab.com/files/file/1148-sexlab-werewolves/
Sexual Vampire Feed https://www.loverslab.com/files/file/9933-sexual-vampire-feed-se/
Sexlab Deadly Drain https://www.loverslab.com/files/file/9905-sexlab-deadly-drain-sse-port/

**Comment by TwistedModding** [comment]
I'll add sexual vampire feed, but not the others.

**Comment by TwistedModding** [comment]
done
