### ISSUE TITLE
Mod Suggestion - Armor Suggestions - Multiple

### ISSUE THREAD

**Issue by cepritchard** [TwistedModding/LSSE#6]
The Amazing World of Bikini Armors REMASTERED by SunJeong
Ninirim Collection 6.0 by SunJeong

Basically you could add nearly every CBBE 3BA mod by Rektas and/or SunJeong.

**Comment by TwistedModding** [comment]
Not going to include ninirim collection, i dont like those armors.

I'll think about the amazing world of bikini armors.

**Comment by Rubret** [comment]
I vote for normal LS3 armors/clothes.  Maybe I’m the only one, but coming across lady jiggle-tits of jiggle-run just doesn’t seem right — I like it to look like LS3 most of the time.  Otherwise I could just play D&D.

**Comment by Rubret** [comment]
...Or maybe there would be a way to please both the normal and the skimpy armor camps by including instructions on how to revert the armors back to normal LS3 armor if skimpy is the default, or vice versa.

**Comment by TwistedModding** [comment]
ive decided im not using the amazing world of bikini armors
